@startuml
class ConexaoBancoDeDados {
    - conexao
    + __construct()
    + obterConexao()
    + __destruct()
    - conectar()
}

class Aluno {
    - conexao
    + __construct()
    + obterListaDeAlunos()
    + obterTrancarMatricula(id)
    - listaAlunos()
    - trancarMatricula(idAluno)
}

class Venda {
    - conn
    + __construct()
    + registrarVenda()
}

class Produtos {
    - conexao
    + __construct()
    + obterProdutos()
    + novoProduto()
    + fazerDelecaoProduto(id)
    - criarProduto()
    - listaDeProdutos()
    - deletarProduto()
    - pesquisarProduto()
}

class Pagamento {
    - conexao
    + __construct()
    + registrarPagamento()
    - registrarPgtoMensalidade()
}

class RelatorioVendas {
    - conn
    + __construct()
    + gerarRelatorio()
}

class Login {
    - conexao
    + __construct()
    + verificarCredenciais()
    + verificarLogin()
    + logout()
    + __destruct()
}

Aluno ..> ConexaoBancoDeDados : usa
Venda ..> ConexaoBancoDeDados : usa
Produtos ..> ConexaoBancoDeDados : usa
Pagamento ..> ConexaoBancoDeDados : usa
RelatorioVendas ..> ConexaoBancoDeDados : usa
Login ..> ConexaoBancoDeDados : usa
@enduml
