@startuml
skinparam actorStyle awesome
actor Usuario as usuario

usuario -> login : verificarLogin
alt usuário já autenticado
    login --> usuario : Usuário já logado

else usuário não autenticado
    usuario -> login : inserir credenciais
    login -> Banco_de_Dados : conectar
    Banco_de_Dados --> login : conexão estabelecida
    alt credenciais válidas
        login --> usuario : Autenticação bem-sucedida
    else credenciais inválidas
        login --> usuario : Falha na autenticação
    end
end

usuario -> login : logout
login -> Banco_de_Dados : desconectar
login --> usuario : Sessão encerrada
@enduml
